### ISSUE TITLE
ShortX发现页面一些指令下载版本失败

### ISSUE THREAD

**Issue by mymine** [Memory2314/Memory-SimpleHook#1]
ShortX发现页面一些指令下载版失败
下载或者添加指令
指令动作中有"显示悬浮工具"，"点击视图ID"等动作时出现
提示:你正在体验免费版，升级到高级版可以解锁全部功能

**Comment by Memory2314** [comment]
> ShortX发现页面一些指令下载版失败
> 下载或者添加指令
> 指令动作中有"显示悬浮工具"，"点击视图ID"等动作时出现
> 提示:你正在体验免费版，升级到高级版可以解锁全部功能

收到，解决了叫你

**Comment by mymine** [comment]
> > ShortX发现页面一些指令下载版失败
> > 下载或者添加指令
> > 指令动作中有"显示悬浮工具"，"点击视图ID"等动作时出现
> > 提示:你正在体验免费版，升级到高级版可以解锁全部功能
> 
> 收到，解决了叫你

好的

**Comment by Memory2314** [comment]
> > > ShortX发现页面一些指令下载版失败
> > > 下载或者添加指令
> > > 指令动作中有"显示悬浮工具"，"点击视图ID"等动作时出现
> > > 提示:你正在体验免费版，升级到高级版可以解锁全部功能
> > 
> > 收到，解决了叫你
> 
> 好的

抱歉，无法解决

**Comment by mymine** [comment]
> > > > ShortX发现页面一些指令下载版失败
> > > > 下载或者添加指令
> > > > 指令动作中有"显示悬浮工具"，"点击视图ID"等动作时出现
> > > > 提示:你正在体验免费版，升级到高级版可以解锁全部功能
> > > 
> > > 
> > > 收到，解决了叫你
> > 
> > 
> > 好的
> 
> 抱歉，无法解决

好的，其他能用就行了。
